name: test
on:
  push:

jobs:
  download:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Download .pkg file
        run: wget https://github.com/slashmo/swift-versions/releases/download/5.6.1-1/swift-5.6.1-RELEASE-osx.pkg
